<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mib</string>
	</array>
	<key>name</key>
	<string>MIB</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\s*--.*?(--|$)</string>
			<key>name</key>
			<string>comment.source.mib</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ACCESS|ANY|AUGMENTS|BEGIN|BIT|BITS|BOOLEAN|CHOICE|COMPONENTS|CONTACT-INFO|DEFINITIONS|DEFVAL|DESCRIPTION|DISPLAY-HINT|END|ENTERPRISE|EXTERNAL|FALSE|FROM|GROUP|IMPLICIT|IMPLIED|IMPORTS|INDEX|LAST-UPDATED|MANDATORY-GROUPS|MAX-ACCESS|MIN-ACCESS|MODULE-COMPLIANCE|MODULE-IDENTITY|MODULE|NOTIFICATION-GROUP|NOTIFICATION-TYPE|NOTIFICATIONS|NULL|OBJECT-GROUP|OBJECT-IDENTITY|OBJECT-TYPE|OBJECTS|OF|OPTIONAL|ORGANIZATION|REFERENCE|REVISION|SEQUENCE|SET|SIZE|STATUS|SYNTAX|TEXTUAL-CONVENTION|TRAP-TYPE|TRUE|UNITS|VARIABLES|WRITE-SYNTAX)\b</string>
			<key>name</key>
			<string>keyword.source.mib</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(DisplayString|INTEGER|Counter|Gauge|IpAddress|OCTET STRING|TimeTicks|RowStatus|TruthValue|UInteger32|Unsigned32|Integer32|Counter32|TestAndIncr|TimeStamp|InstancePointer|OBJECT IDENTIFIER|Gauge32|AutonomousType|Counter64|PhysAddress|TimeInterval|MacAddress|StorageType|RowPointer|TDomain|TAddress)\b</string>
			<key>name</key>
			<string>storage.type.source.mib</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(accessible-for-notify|current|deprecated|mandatory|not-accessible|obsolete|optional|read-create|read-only|read-write|write-only|experimental|mib-2|snmpModules|ifIndex)\b</string>
			<key>name</key>
			<string>storage.modifier.source.mib</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.source.mib</string>
		</dict>
		<dict>
			<key>match</key>
			<string>::=</string>
			<key>name</key>
			<string>keyword.operator.source.mib</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&lt;['0-9a-fA-FhH]*\&gt;</string>
			<key>name</key>
			<string>constant.numeric.source.mib</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|\v|\s|)[0-9]+(\s|,|$)</string>
			<key>name</key>
			<string>constant.numeric.source.mib</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(([0-9]+)((\.\.|\s*\|\s*)([0-9]+))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.source.mib</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.source.mib</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>variable.complex.mib</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mib</string>
	<key>uuid</key>
	<string>2181e397-12a9-4cfe-8129-7b7e932fbab2</string>
</dict>
</plist>
